apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-hostname-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: drogon
  template:
    metadata:
      labels:
        app: drogon
    spec:
      containers:
        - name: drogon-server
          image: cpp-hostname-k8s:local
          imagePullPolicy: IfNotPresent # Использовать локальный образ
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          livenessProbe: # Проверка здоровья
            httpGet:
              path: /api/hostname
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
